version: '3.8'
services:
  main-site:
    build:
      context: ./main-site
    ports:
      - "8080:80"
    volumes:
      - ./main-site/public:/var/www/html
  sub-main-site:
    build:
      context: ./sub.main-site
    ports:
      - "8081:80"
    volumes:
      - ./sub.main-site/public:/var/www/html
  cross-site:
    build:
      context: ./cross-site
    ports:
      - "8082:80"
    volumes:
      - ./cross-site/public:/var/www/html